language: crystal
script:
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: tinkerforge
  keep_history: true
  on:
    branch: master
  local_dir: docs
